name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Verify Script Syntax
      run: node -c index.js
    
    - name: Run tests
      run: npm run test:run
    
    - name: Test package creation
      run: npm pack
    
    - name: Test global install
      shell: bash
      run: |
        npm install -g ./claude-mcp-quickstart-*.tgz
        claude-mcp-quickstart --version
    
    - name: Test CLI commands from different directories
      shell: bash
      run: |
        # Test from home directory
        cd ~
        claude-mcp-quickstart verify || true
        
        # Test from temporary directory 
        cd /tmp
        claude-mcp-quickstart --version
        
        # Test template access works (critical fix verification)
        echo "Testing template access from different directory..."
        mkdir -p test-templates
        cd test-templates
        echo "Current directory: $(pwd)"
        # Test template access - should succeed with proper exit code
        if timeout 10s claude-mcp-quickstart setup </dev/null; then
          echo "Template access test: PASSED"
        else
          echo "Template access test: FAILED (expected for interactive setup)"
        fi
      continue-on-error: true
