# .github/workflows/cross-platform-performance.yml
name: Cross-Platform Performance Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

jobs:
  performance-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run performance benchmarks
      run: npm run benchmark

    - name: Cross-platform consistency check
      run: node cross-platform-validator.js

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results-${{ matrix.os }}-${{ matrix.node-version }}
        path: .performance/

  consistency-analysis:
    needs: performance-matrix
    runs-on: ubuntu-latest
    steps:
    - name: Download all results
      uses: actions/download-artifact@v4

    - name: Analyze cross-platform consistency
      run: node analyze-platform-consistency.js

    - name: Generate consistency report
      run: node generate-consistency-report.js